#服务器配置
server:
    port: 8888
    undertow:
        threads:
            # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
            io: 16
            # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
            worker: 400
        # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
        buffer-size: 1024
        # 是否分配的直接内存
        direct-buffers: true
        max-http-post-size: -1B

spring:
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #driver-class-name: org.postgresql.Driver
        #driver-class-name: oracle.jdbc.OracleDriver
        #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        #driver-class-name: dm.jdbc.driver.DmDriver
        druid:
            # MySql、PostgreSQL、SqlServer、DaMeng校验
            validation-query: select 1
            # Oracle校验
            #validation-query: select 1 from dual
            validation-query-timeout: 2000
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 300000
            min-evictable-idle-time-millis: 300000
            stat-view-servlet:
                enabled: true
                login-username: lecent
                login-password: lecent2022
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
                session-stat-enable: true
                session-stat-max-count: 10

# mybatis
mybatis-plus:
    mapper-locations: classpath:com/springboot.pure/**/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: org.springboot.**.entity
    #typeEnumsPackage: org.springblade.dashboard.entity.enums
    global-config:
        # 关闭MP3.0自带的banner
        banner: false
        db-config:
            #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
            id-type: assign_id
            #字段策略
            insert-strategy: not_null
            update-strategy: not_null
            where-strategy: not_null
            #驼峰下划线转换
            table-underline: true
            # 逻辑删除配置
            # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
            logic-delete-value: 1
            # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
            logic-not-delete-value: 0
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        jdbc-type-for-null: 'null'

# 健康检查
management:
    server:
        port: 8081
    endpoint:
        health:
            show-details: always
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: '*'